default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: foodojo_development

test:
  <<: *default
  database: foodojo_test

production: &production
  <<: *default
  database: foodojo_production

integration:
  <<: *production
  database: foodojo_integration

staging:
  <<: *production
  database: foodojo_staging
